### PR TITLE
fixes language code for Greek

### LINKED ISSUE #97: GR is not a valid ISO language code - use EL instead
Caught here:

https://rocketvalidator.com/s/0bdee490-cff7-495a-95a3-40211cd2b5cd/i/112946387

Correct code for Greek seems to be `el`.

### PR DESCRIPTION
**Pull request by jaimeiniesta**
According to 

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

the correct 2 letter code for modern Greek is `el`, not `gr`

@doomspork maybe this should be fixed also in the main repo so when we copy content, we rename the `gr` folder to `el`. I've already done that on the Makefile, so removing the `content` folder and running `make content` again also works.

closes #97

### CODE REVIEW

File: config/config.exs [hunk 1]
```diff
@@ -33,7 +33,7 @@ config :phoenix, :json_library, Jason
 
 config :school_house, SchoolHouseWeb.Gettext,
   default_locale: "en",
-  locales: ~w(ar bg bn de en es fr gr id it ja ko ms no pl pt ru sk ta th tr uk vi zh-hans zh-hant)
+  locales: ~w(ar bg bn de en es fr el id it ja ko ms no pl pt ru sk ta th tr uk vi zh-hans zh-hant)
 
 import_config "lessons.exs"
 import_config "redirects.exs"
```
Comment (doomspork) [inline config/config.exs:39]: We need to update the redirect file so that `gr` goes to `el` too.

**Review by doomspork — COMMENTED** [review]
@gemantzu how did we get this one wrong? 😆

File: config/config.exs (hunk 1 above)
Comment (jaimeiniesta) [reply config/config.exs:39]: Done!

**Comment by doomspork** [comment]
I disabled the PR deployments until I can figure that out. Glancing at the logs it appears to be a config thing. We're using Heroku's containers but the PR app is looking for the buildpack and language setup.

File: Makefile [hunk 2]
```diff
@@ -8,6 +8,7 @@ content:
 	rm -rf content assets/static/images
 	git clone --branch content-only-changes --single-branch --depth 1 https://github.com/elixirschool/elixirschool.git content
 	mv content/images assets/static/images
+	mv content/lessons/gr content/lessons/el
```
Comment (doomspork) [inline Makefile:11]: We don't need this. I'm going to address this in the content branch. It will be broken until I get that rebased and fixed though.

**Comment by gemantzu** [comment]
I said this a while ago, but I don't remember why we did nothing. It's not that big of a deal, but thankfully someone came up and solved it :)

File: Makefile (hunk 2 above)
Comment (jaimeiniesta) [reply Makefile]: OK I removed that line.

File: config/config.exs [hunk 3]
```diff
@@ -33,7 +33,7 @@ config :phoenix, :json_library, Jason
 
 config :school_house, SchoolHouseWeb.Gettext,
   default_locale: "en",
-  locales: ~w(ar bg bn de en es fr gr id it ja ko ms no pl pt ru sk ta th tr uk vi zh-hans zh-hant)
+  locales: ~w(ar bg bn de en es fr el id it ja ko ms no pl pt ru sk ta th tr uk vi zh-hans zh-hant)
```
Comment (kinson) [inline config/config.exs:36]:
```suggestion
  locales: ~w(ar bg bn de el en es fr id it ja ko ms no pl pt ru sk ta th tr uk vi zh-hans zh-hant)
```

Very nitpicky, but it might be nice to maintain the alphabetization of this list 🤷🏼

Comment (jaimeiniesta) [reply config/config.exs]: 👌  @kinson

**Review by kinson — APPROVED** [review]
@doomspork I'll wait to test out my merge powahs on another pr in case you want one more look at this first!

File: config/config.exs (hunk 3 above)
Comment (doomspork) [reply config/config.exs]: Thanks you two ❤️
