### PR TITLE
We only need to modify the path

### LINKED ISSUE #22: Broken links to port 80
I've run a Rocket Validator report on the beta site, and the crawler has found some broken links, on pages that use the `80` port:

https://rocketvalidator.com/s/5a71bc62-29c6-4e85-9ce5-2af0513f1976

Not sure yet if these are direct links or redirections, any idea?

### PR DESCRIPTION
**Pull request by doomspork**
Update the function to `_url` from `_link` to more accurately reflect
what it does. Only modify the request path, the entire url is not
necessary. 

Fixes #22.

### CODE REVIEW

**Comment by doomspork** [comment]
@jaimeiniesta this should address the issue you found in the locale menu with the port being present (unlike other urls on the page). I also took this time to rename this function so its purpose is clearer.

**Comment by jaimeiniesta** [comment]
This ain't gonna work because `String.replace` is going to replace **all** the occurrences, so if you're for instance at:

`http://localhost:4000/es/ecto/changesets`

And you change the locale to `fr`, it's going to take you to:

`http://localhost:4000/fr/ecto/changfrets`

A workaround could be:

```elixir
def current_page_locale_path(%{request_path: request_path}, locale) do
  String.replace(request_path, current_locale(), locale, global: false)
end
```

**Comment by doomspork** [comment]
Good catch. This bug definitely exists in the current code too. I used `String.replace_prefix/3` and added a basic test as well. I've been "moving fast and breaking things" but I'll slow down and write some better test coverage now that yourself and others may be interested in contributing :tada:

File: lib/school_house_web/views/html_helpers.ex [hunk 1]
```diff
@@ -9,9 +9,8 @@ defmodule SchoolHouseWeb.HtmlHelpers do
 
   def avatar_url(github_link), do: "#{github_link}.png"
 
-  def current_page_locale_link(conn, locale) do
-    current_url = Phoenix.Controller.current_url(conn)
-    String.replace(current_url, current_locale(), locale)
+  def current_page_locale_path(%{request_path: request_path}, locale) do
+    String.replace_prefix(request_path, current_locale(), locale)
```
Comment (jaimeiniesta) [inline lib/school_house_web/views/html_helpers.ex:13]: I'm afraid this won't work, because the `request_path` includes a slash:

```elixir
iex> String.replace_prefix("/en", "en", "es")
"/en"
```

File: test/school_house_web/views/html_helpers_test.exs [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+      assert "https://github.com/elixirschool.png" == HtmlHelpers.avatar_url("https://github.com/elixirschool")
+    end
+  end
+
+  describe "current_page_locale_path/2" do
+    test "returns the current page path for another locale" do
+      Gettext.put_locale("es")
+
+      assert "fr/ecto/changesets" ==
+               HtmlHelpers.current_page_locale_path(%Plug.Conn{request_path: "es/ecto/changesets"}, "fr")
```
Comment (jaimeiniesta) [inline test/school_house_web/views/html_helpers_test.exs:17]: This test doesn't reflect real world usage, as `request_path` will include the leading slash: `/es/ecto/changesets`.

So the test should be:

```elixir
assert "/fr/ecto/changesets" ==
               HtmlHelpers.current_page_locale_path(%Plug.Conn{request_path: "/es/ecto/changesets"}, "fr")
```

File: lib/school_house_web/views/html_helpers.ex (hunk 1 above)
Comment (jaimeiniesta) [reply lib/school_house_web/views/html_helpers.ex:13]: This works:

```elixir
String.replace_prefix(request_path, "/#{current_locale()}", "/#{locale}")
```

**Review by jaimeiniesta — CHANGES_REQUESTED** [review]

File: test/school_house_web/views/html_helpers_test.exs (hunk 2 above)
Comment (doomspork) [reply test/school_house_web/views/html_helpers_test.exs]: I updated the tests to use the ConnTest and `build_conn` to make this more accurate and less reliant on building things up manually which opens up opportunities for issues like this.

File: test/school_house_web/views/html_helpers_test.exs [hunk 3]
```diff
@@ -0,0 +1,57 @@
+defmodule SchoolHouseWeb.HtmlHelpersTest do
```
Comment (doomspork) [inline test/school_house_web/views/html_helpers_test.exs:1]: There's one more remaining function in the HtmlHelpers module that needs test coverage. I'll take care of that later.

**Comment by doomspork** [comment]
Something I noticed while writing these tests and working on some others: we may want to find a way to put a scaled down collection of lessons in a template folder within `test` to speed things up. Right now changes require a complete recompilation of _all_ lessons and blogs, which is hefty. Still faster than Jekyll but that's a low bar.

File: test/school_house_web/views/html_helpers_test.exs [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+               |> HtmlHelpers.current_page_locale_path("fr")
+    end
+  end
+
+  describe "supported_locales/0" do
+    test "returns a list of all supported locales" do
+      locales = HtmlHelpers.supported_locales()
+
+      assert is_list(locales)
+      assert 1 < length(locales)
```
Comment (doomspork) [inline test/school_house_web/views/html_helpers_test.exs:54]: This is pretty simple. I was originally going to check for inclusion of some known locales (en, es, gr for instance) but I'm not sure that adds much and I worry it may result in churn as folks see the test and continue to add locales.

File: lib/school_house_web/templates/layout/_locale_menu.html.leex [hunk 5]
```diff
@@ -10,7 +10,7 @@
     <div x-show="isOpen" @click.away=" { isOpen = false } " class="origin-top-right absolute left-0 mt-2 w-24 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
         <div class="py-1" role="none">
         <%= for locale <- supported_locales() do %>
-            <a href="<%= current_page_locale_link(@conn, locale) %>" class="block px-4 py-2 text-sm text-gray-700 hover:bg-brand-light-gray hover:font-bold" role="menuitem"><%= locale %></a>
+            <a href="<%= current_page_locale_path(@conn, locale) %>" class="block px-4 py-2 text-sm text-gray-700 hover:bg-brand-light-gray hover:font-bold" role="menuitem"><%= locale %></a>
```
Comment (doomspork) [inline lib/school_house_web/templates/layout/_locale_menu.html.leex:13]: Potential future improvement is pulling this whole piece out into a `link` function that builds the markup. Since we use the Phoenix helpers elsewhere it may make sense to follow that pattern here for consistency sake.

File: lib/school_house_web/views/html_helpers.ex [hunk 6]
```diff
@@ -9,9 +9,8 @@ defmodule SchoolHouseWeb.HtmlHelpers do
 
   def avatar_url(github_link), do: "#{github_link}.png"
 
-  def current_page_locale_link(conn, locale) do
-    current_url = Phoenix.Controller.current_url(conn)
-    String.replace(current_url, current_locale(), locale)
+  def current_page_locale_path(%{request_path: request_path}, locale) do
```
Comment (doomspork) [inline lib/school_house_web/views/html_helpers.ex:12]: I'm open to either or on this but I'd love to get your feedback @jaimeiniesta:

Do you have any strong feelings about matches like this including the struct or are maps fine? Folks seem to prefer one or the other and before we get too far I wanted to address that.

Expressed in code:

```elixir
def current_page_locale_path(%Plug.Conn{request_path: request_path}, locale) do

def current_page_locale_path(%{request_path: request_path}, locale) do
````

File: test/school_house_web/views/html_helpers_test.exs [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+  end
+
+  describe "current_locale/0" do
+    setup do
+      Gettext.put_locale("es")
+
+      on_exit(fn ->
+        Gettext.put_locale("en")
+      end)
+    end
```
Comment (doomspork) [inline test/school_house_web/views/html_helpers_test.exs:19]: This could potentially live at the top of the file since. We can always rely on the `es` locale in testing since it has great coverage in the lessons.

File: lib/school_house_web/views/html_helpers.ex (hunk 6 above)
Comment (gemantzu) [reply lib/school_house_web/views/html_helpers.ex:12]: I prefer the maps most of the time, as this is internal code and we are only increasing complexity / adding dependency on another module without reason. Map matching should be enough.

File: test/school_house_web/views/html_helpers_test.exs (hunk 4 above)
Comment (gemantzu) [reply test/school_house_web/views/html_helpers_test.exs:46]: nah, don't overcomplicate this, if there is a known bug we will take care of it later via a new test case.

File: lib/school_house_web/views/html_helpers.ex (hunk 6 above)
Comment (doomspork) [reply lib/school_house_web/views/html_helpers.ex:12]: Thanks for chiming in @gemantzu :tada: 

That is kind of my thinking too. On one hand using the struct makes the code's intention clearer. On the other though, it can really start to clutter up code and it adds the tiniest bit of extra work to testing these functions directly.

Comment (gemantzu) [reply lib/school_house_web/views/html_helpers.ex:12]: yeah, this can come to bite us, even though I don't see this project being that big to be too much of an issue tbh.

Comment (jaimeiniesta) [reply lib/school_house_web/views/html_helpers.ex:12]: Yes I also think that maps are good enough for this. We just care about the `:request_path` key being present, not so much about the exact module.

Comment (doomspork) [reply lib/school_house_web/views/html_helpers.ex:12]: Thank you for the input @jaimeiniesta and @gemantzu. It shall be so :tada:

**Review by jaimeiniesta — APPROVED** [review]
